# -*- coding: utf-8 -*-
"""simplecalcuprgm

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g0RHiZ1teJYrKmmL2kG8PZ4LxV0Z9ANT
"""

def add(a,b):
  print("a+b =",a+b)
def sub(a,b):
  print("a-b =",a-b)
def mul(a,b):
  print("a*b =",a*b)
def div(a,b):
  print("a/b =",a/b)   
a= int(input("Enter the first number:"))        
b= int(input("Enter the second number:"))

c= int(input("Enter your choice 1.Add 2.Subtract 3.Multiply 4.Divide:"))
if c==1:
  add(a,b)
elif c==2:
  sub(a,b)
elif c==3:  
  mul(a,b)
elif c==4:
  div(a,b)
else:
  print("Enter valid choice number")